"""new fifa data

Revision ID: cc41487c95da
Revises: 91aa76502da2
Create Date: 2019-03-14 17:05:37.913000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc41487c95da'
down_revision = '91aa76502da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fifa', sa.Column('ID', sa.Integer(), nullable=False))
    op.drop_column('fifa', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fifa', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('fifa', 'ID')
    # ### end Alembic commands ###
